apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      foo: bar
  replicas: 1
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
        - name: app
          # This is the import path for the Go binary to build and run.
          image: ko://github.com/alitari/kogo/src/app
